export type StarterTemplateVariant = {
  label: string;
  buyPrice?: number | null;
  sellPrice: number;
  openingStock?: number | null;
  sku?: string | null;
  barcode?: string | null;
  sortOrder?: number;
  isActive?: boolean;
};

export type StarterBusinessProductTemplate = {
  businessType: string;
  name: string;
  brand?: string | null;
  category?: string | null;
  packSize?: string | null;
  defaultBuyPrice?: number | null;
  defaultSellPrice?: number | null;
  defaultOpeningStock?: number | null;
  defaultBarcode?: string | null;
  defaultBaseUnit?: string | null;
  defaultTrackStock?: boolean;
  aliases?: string[];
  keywords?: string[];
  variants?: StarterTemplateVariant[];
  imageUrl?: string | null;
  popularityScore?: number;
  isActive?: boolean;
};

export const STARTER_BUSINESS_PRODUCT_TEMPLATES: StarterBusinessProductTemplate[] = [
  {
    businessType: "tea_stall",
    name: "Milk Tea",
    category: "Beverages",
    defaultSellPrice: 25,
    aliases: ["dudh cha", "tea"],
    keywords: ["tea", "hot", "drink"],
    popularityScore: 98,
  },
  {
    businessType: "tea_stall",
    name: "Black Tea",
    category: "Beverages",
    defaultSellPrice: 20,
    aliases: ["rong cha", "black tea"],
    keywords: ["tea", "hot", "drink"],
    popularityScore: 92,
  },
  {
    businessType: "tea_stall",
    name: "Coffee",
    category: "Beverages",
    defaultSellPrice: 40,
    aliases: ["black coffee", "hot coffee"],
    keywords: ["coffee", "drink"],
    popularityScore: 86,
  },
  {
    businessType: "tea_stall",
    name: "Lemon Tea",
    category: "Beverages",
    defaultSellPrice: 30,
    aliases: ["lebu tea", "lemon cha"],
    keywords: ["tea", "lemon", "drink"],
    popularityScore: 78,
  },
  {
    businessType: "tea_stall",
    name: "Toast Biscuit",
    brand: "Olympic",
    category: "Snacks",
    packSize: "1 pack",
    defaultSellPrice: 10,
    defaultBarcode: "2800000000001",
    aliases: ["biscuit", "toast"],
    keywords: ["snacks", "tea stall", "biscuit"],
    popularityScore: 72,
  },
  {
    businessType: "sweet_shop",
    name: "রসগোল্লা",
    category: "মিষ্টি",
    defaultBuyPrice: 180,
    defaultSellPrice: 280,
    defaultBaseUnit: "kg",
    aliases: ["rosogolla", "rasgulla"],
    keywords: ["sweet shop", "mishti", "kg"],
    popularityScore: 98,
  },
  {
    businessType: "sweet_shop",
    name: "কালোজাম",
    category: "মিষ্টি",
    defaultBuyPrice: 190,
    defaultSellPrice: 300,
    defaultBaseUnit: "kg",
    aliases: ["kalojam", "kalo jam"],
    keywords: ["sweet shop", "mishti", "kg"],
    popularityScore: 94,
  },
  {
    businessType: "sweet_shop",
    name: "চমচম",
    category: "মিষ্টি",
    defaultBuyPrice: 200,
    defaultSellPrice: 320,
    defaultBaseUnit: "kg",
    aliases: ["chomchom", "chamcham"],
    keywords: ["sweet shop", "mishti", "kg"],
    popularityScore: 90,
  },
  {
    businessType: "sweet_shop",
    name: "সন্দেশ",
    category: "মিষ্টি",
    defaultBuyPrice: 240,
    defaultSellPrice: 380,
    defaultBaseUnit: "kg",
    aliases: ["sandesh"],
    keywords: ["sweet shop", "mishti", "premium"],
    popularityScore: 86,
  },
  {
    businessType: "sweet_shop",
    name: "লাড্ডু",
    category: "মিষ্টি",
    defaultBuyPrice: 170,
    defaultSellPrice: 260,
    defaultBaseUnit: "kg",
    aliases: ["laddu", "ladoo"],
    keywords: ["sweet shop", "mishti"],
    popularityScore: 82,
  },
  {
    businessType: "sweet_shop",
    name: "জিলাপি",
    category: "মিষ্টি",
    defaultBuyPrice: 140,
    defaultSellPrice: 220,
    defaultBaseUnit: "kg",
    aliases: ["jilapi", "jalebi"],
    keywords: ["sweet shop", "hot sweet", "kg"],
    popularityScore: 88,
  },
  {
    businessType: "sweet_shop",
    name: "মিষ্টি দই",
    category: "দই",
    defaultBaseUnit: "pcs",
    defaultTrackStock: true,
    aliases: ["mishti doi", "sweet curd"],
    keywords: ["sweet shop", "doi", "curd"],
    variants: [
      { label: "কাপ", buyPrice: 18, sellPrice: 30, openingStock: 24, sortOrder: 0 },
      { label: "500g", buyPrice: 75, sellPrice: 120, openingStock: 12, sortOrder: 1 },
      { label: "1kg", buyPrice: 140, sellPrice: 220, openingStock: 8, sortOrder: 2 },
    ],
    popularityScore: 92,
  },
  {
    businessType: "sweet_shop",
    name: "টক দই",
    category: "দই",
    defaultBaseUnit: "pcs",
    defaultTrackStock: true,
    aliases: ["tok doi", "sour curd"],
    keywords: ["sweet shop", "doi", "curd"],
    variants: [
      { label: "500g", buyPrice: 60, sellPrice: 100, openingStock: 10, sortOrder: 0 },
      { label: "1kg", buyPrice: 110, sellPrice: 180, openingStock: 6, sortOrder: 1 },
    ],
    popularityScore: 76,
  },
  {
    businessType: "sweet_shop",
    name: "সমুচা",
    category: "নাস্তা",
    defaultBuyPrice: 8,
    defaultSellPrice: 15,
    defaultBaseUnit: "pcs",
    aliases: ["samosa", "somucha"],
    keywords: ["sweet shop", "snacks", "pcs"],
    popularityScore: 90,
  },
  {
    businessType: "sweet_shop",
    name: "সিঙ্গারা",
    category: "নাস্তা",
    defaultBuyPrice: 7,
    defaultSellPrice: 12,
    defaultBaseUnit: "pcs",
    aliases: ["singara"],
    keywords: ["sweet shop", "snacks", "pcs"],
    popularityScore: 86,
  },
  {
    businessType: "sweet_shop",
    name: "নিমকি প্যাকেট",
    category: "প্যাকেট আইটেম",
    packSize: "250g",
    defaultBuyPrice: 55,
    defaultSellPrice: 90,
    defaultOpeningStock: 12,
    defaultBarcode: "2800000000339",
    defaultBaseUnit: "packet",
    defaultTrackStock: true,
    aliases: ["nimki", "nimki pack"],
    keywords: ["sweet shop", "packet", "snacks"],
    popularityScore: 78,
  },
  {
    businessType: "sweet_shop",
    name: "বিস্কুট বক্স",
    category: "বেকারি",
    packSize: "1 box",
    defaultBuyPrice: 160,
    defaultSellPrice: 240,
    defaultOpeningStock: 8,
    defaultBarcode: "2800000000346",
    defaultBaseUnit: "box",
    defaultTrackStock: true,
    aliases: ["biscuit box", "bakery biscuit"],
    keywords: ["sweet shop", "bakery", "box"],
    popularityScore: 72,
  },
  {
    businessType: "sweet_shop",
    name: "পানির বোতল",
    category: "প্যাকেট আইটেম",
    packSize: "500ml",
    defaultBuyPrice: 12,
    defaultSellPrice: 20,
    defaultOpeningStock: 24,
    defaultBarcode: "2800000000353",
    defaultBaseUnit: "pcs",
    defaultTrackStock: true,
    aliases: ["water", "mineral water"],
    keywords: ["sweet shop", "drink", "water"],
    popularityScore: 70,
  },
  {
    businessType: "food_cart",
    name: "Chicken Burger",
    category: "Fast Food",
    defaultBuyPrice: 65,
    defaultSellPrice: 120,
    aliases: ["burger", "chicken burger"],
    keywords: ["food cart", "fast food", "burger"],
    popularityScore: 98,
  },
  {
    businessType: "food_cart",
    name: "Beef Burger",
    category: "Fast Food",
    defaultBuyPrice: 85,
    defaultSellPrice: 160,
    aliases: ["beef burger"],
    keywords: ["food cart", "fast food", "burger"],
    popularityScore: 90,
  },
  {
    businessType: "food_cart",
    name: "Chicken Roll",
    category: "Roll",
    defaultBuyPrice: 45,
    defaultSellPrice: 80,
    aliases: ["roll", "chicken roll"],
    keywords: ["food cart", "fast food", "roll"],
    popularityScore: 94,
  },
  {
    businessType: "food_cart",
    name: "Egg Roll",
    category: "Roll",
    defaultBuyPrice: 30,
    defaultSellPrice: 60,
    aliases: ["egg roll"],
    keywords: ["food cart", "fast food", "roll"],
    popularityScore: 84,
  },
  {
    businessType: "food_cart",
    name: "French Fries",
    category: "Sides",
    packSize: "1 plate",
    defaultBuyPrice: 35,
    defaultSellPrice: 80,
    aliases: ["fries", "potato fries"],
    keywords: ["food cart", "snacks", "fries"],
    popularityScore: 88,
    variants: [
      { label: "Regular", buyPrice: 35, sellPrice: 80, sortOrder: 0 },
      { label: "Large", buyPrice: 55, sellPrice: 120, sortOrder: 1 },
    ],
  },
  {
    businessType: "food_cart",
    name: "Chicken Nuggets",
    category: "Sides",
    packSize: "6 pcs",
    defaultBuyPrice: 70,
    defaultSellPrice: 140,
    aliases: ["nuggets"],
    keywords: ["food cart", "snacks", "chicken"],
    popularityScore: 78,
  },
  {
    businessType: "food_cart",
    name: "Club Sandwich",
    category: "Fast Food",
    defaultBuyPrice: 70,
    defaultSellPrice: 140,
    aliases: ["sandwich"],
    keywords: ["food cart", "fast food", "sandwich"],
    popularityScore: 76,
  },
  {
    businessType: "food_cart",
    name: "Pasta",
    category: "Fast Food",
    packSize: "1 bowl",
    defaultBuyPrice: 65,
    defaultSellPrice: 130,
    aliases: ["chicken pasta"],
    keywords: ["food cart", "fast food", "pasta"],
    popularityScore: 72,
  },
  {
    businessType: "food_cart",
    name: "Soft Drink",
    category: "Drinks",
    defaultBaseUnit: "pcs",
    defaultTrackStock: true,
    aliases: ["cold drink", "soft drinks"],
    keywords: ["food cart", "drink", "bottle"],
    variants: [
      {
        label: "250ml",
        buyPrice: 17,
        sellPrice: 25,
        openingStock: 24,
        barcode: "2800000000308",
        sortOrder: 0,
      },
      {
        label: "500ml",
        buyPrice: 30,
        sellPrice: 40,
        openingStock: 12,
        barcode: "2800000000315",
        sortOrder: 1,
      },
    ],
    popularityScore: 92,
  },
  {
    businessType: "food_cart",
    name: "Mineral Water",
    category: "Drinks",
    packSize: "500ml",
    defaultBuyPrice: 12,
    defaultSellPrice: 20,
    defaultOpeningStock: 24,
    defaultBarcode: "2800000000322",
    defaultBaseUnit: "pcs",
    defaultTrackStock: true,
    aliases: ["water", "bottled water"],
    keywords: ["food cart", "drink", "water"],
    popularityScore: 86,
  },
  {
    businessType: "food_cart",
    name: "Combo Meal 1",
    category: "Combo",
    packSize: "Burger + fries + drink",
    defaultBuyPrice: 110,
    defaultSellPrice: 199,
    aliases: ["combo", "burger combo"],
    keywords: ["food cart", "combo", "meal"],
    popularityScore: 82,
  },
  {
    businessType: "food_cart",
    name: "Extra Cheese",
    category: "Add-on",
    defaultBuyPrice: 12,
    defaultSellPrice: 25,
    aliases: ["cheese"],
    keywords: ["food cart", "add-on", "extra"],
    popularityScore: 70,
  },
  {
    businessType: "pan_cigarette",
    name: "Gold Leaf Regular",
    brand: "Gold Leaf",
    category: "Cigarette",
    packSize: "10 sticks",
    defaultSellPrice: 20,
    defaultBarcode: "2800000000018",
    aliases: ["goldleaf", "gl regular"],
    keywords: ["cigarette", "smoke"],
    popularityScore: 96,
  },
  {
    businessType: "pan_cigarette",
    name: "Benson Switch",
    brand: "Benson",
    category: "Cigarette",
    packSize: "10 sticks",
    defaultSellPrice: 23,
    defaultBarcode: "2800000000025",
    aliases: ["benson", "switch"],
    keywords: ["cigarette", "smoke"],
    popularityScore: 90,
  },
  {
    businessType: "pan_cigarette",
    name: "Navy Cigarette",
    brand: "Navy",
    category: "Cigarette",
    packSize: "10 sticks",
    defaultSellPrice: 18,
    defaultBarcode: "2800000000032",
    aliases: ["navy"],
    keywords: ["cigarette", "smoke"],
    popularityScore: 82,
  },
  {
    businessType: "pan_cigarette",
    name: "Jarda Paan",
    category: "Paan",
    defaultSellPrice: 15,
    aliases: ["paan", "jorda pan"],
    keywords: ["paan", "betel"],
    popularityScore: 70,
  },
  {
    businessType: "pan_cigarette",
    name: "Mineral Water",
    brand: "Mum",
    category: "Drinks",
    packSize: "500ml",
    defaultSellPrice: 20,
    defaultBarcode: "2800000000049",
    aliases: ["water", "bottled water"],
    keywords: ["drink", "water"],
    popularityScore: 74,
  },
  {
    businessType: "mobile_recharge",
    name: "Grameenphone Flexiload",
    brand: "Grameenphone",
    category: "Recharge",
    defaultSellPrice: 20,
    aliases: ["gp recharge", "gp flexi"],
    keywords: ["mobile", "recharge", "topup"],
    popularityScore: 95,
  },
  {
    businessType: "mobile_recharge",
    name: "Robi Flexiload",
    brand: "Robi",
    category: "Recharge",
    defaultSellPrice: 20,
    aliases: ["robi recharge", "robi flexi"],
    keywords: ["mobile", "recharge", "topup"],
    popularityScore: 90,
  },
  {
    businessType: "mobile_recharge",
    name: "Banglalink Flexiload",
    brand: "Banglalink",
    category: "Recharge",
    defaultSellPrice: 20,
    aliases: ["bl recharge", "banglalink flexi"],
    keywords: ["mobile", "recharge", "topup"],
    popularityScore: 88,
  },
  {
    businessType: "mobile_recharge",
    name: "Airtel Flexiload",
    brand: "Airtel",
    category: "Recharge",
    defaultSellPrice: 20,
    aliases: ["airtel recharge"],
    keywords: ["mobile", "recharge", "topup"],
    popularityScore: 74,
  },
  {
    businessType: "mobile_recharge",
    name: "Teletalk Flexiload",
    brand: "Teletalk",
    category: "Recharge",
    defaultSellPrice: 20,
    aliases: ["tt recharge", "teletalk recharge"],
    keywords: ["mobile", "recharge", "topup"],
    popularityScore: 58,
  },
  {
    businessType: "fruits_veg",
    name: "Potato",
    category: "Vegetables",
    defaultSellPrice: 60,
    defaultBaseUnit: "kg",
    defaultTrackStock: true,
    aliases: ["alu"],
    keywords: ["vegetable", "fresh"],
    popularityScore: 96,
  },
  {
    businessType: "fruits_veg",
    name: "Onion",
    category: "Vegetables",
    defaultSellPrice: 90,
    defaultBaseUnit: "kg",
    defaultTrackStock: true,
    aliases: ["peyaj"],
    keywords: ["vegetable", "fresh"],
    popularityScore: 94,
  },
  {
    businessType: "fruits_veg",
    name: "Tomato",
    category: "Vegetables",
    defaultSellPrice: 80,
    defaultBaseUnit: "kg",
    defaultTrackStock: true,
    aliases: ["tomato"],
    keywords: ["vegetable", "fresh"],
    popularityScore: 88,
  },
  {
    businessType: "fruits_veg",
    name: "Green Chili",
    category: "Vegetables",
    defaultSellPrice: 120,
    defaultBaseUnit: "kg",
    defaultTrackStock: true,
    aliases: ["kancha morich"],
    keywords: ["vegetable", "fresh"],
    popularityScore: 80,
  },
  {
    businessType: "fruits_veg",
    name: "Banana",
    category: "Fruits",
    defaultSellPrice: 12,
    defaultBaseUnit: "pcs",
    defaultTrackStock: true,
    aliases: ["kola"],
    keywords: ["fruit", "fresh"],
    popularityScore: 84,
  },
  {
    businessType: "snacks_stationery",
    name: "Potato Chips",
    brand: "Lays",
    category: "Snacks",
    packSize: "25g",
    defaultSellPrice: 20,
    defaultBarcode: "2800000000056",
    aliases: ["chips"],
    keywords: ["snacks", "packet"],
    popularityScore: 90,
  },
  {
    businessType: "snacks_stationery",
    name: "Chanachur Pack",
    brand: "Pran",
    category: "Snacks",
    packSize: "35g",
    defaultSellPrice: 15,
    defaultBarcode: "2800000000063",
    aliases: ["chanachur"],
    keywords: ["snacks", "packet"],
    popularityScore: 82,
  },
  {
    businessType: "snacks_stationery",
    name: "Ball Pen",
    brand: "Matador",
    category: "Stationery",
    defaultSellPrice: 10,
    aliases: ["pen"],
    keywords: ["stationery", "writing"],
    popularityScore: 88,
  },
  {
    businessType: "snacks_stationery",
    name: "Notebook",
    brand: "Fresh",
    category: "Stationery",
    packSize: "80 pages",
    defaultSellPrice: 35,
    aliases: ["khata"],
    keywords: ["stationery", "copy", "school"],
    popularityScore: 76,
  },
  {
    businessType: "snacks_stationery",
    name: "Chocolate Bar",
    brand: "Dairy Milk",
    category: "Snacks",
    packSize: "24g",
    defaultSellPrice: 50,
    defaultBarcode: "2800000000070",
    aliases: ["chocolate"],
    keywords: ["snacks", "sweet"],
    popularityScore: 74,
  },
  {
    businessType: "mini_grocery",
    name: "Miniket Rice",
    brand: "ACI",
    category: "Staples",
    packSize: "5kg",
    defaultSellPrice: 420,
    defaultBarcode: "2800000000087",
    defaultBaseUnit: "kg",
    defaultTrackStock: true,
    aliases: ["chal", "rice"],
    keywords: ["grocery", "staple", "daily"],
    popularityScore: 98,
  },
  {
    businessType: "mini_grocery",
    name: "Soybean Oil",
    brand: "Fresh",
    category: "Oil",
    packSize: "1L",
    defaultSellPrice: 195,
    defaultBarcode: "2800000000094",
    defaultBaseUnit: "liter",
    defaultTrackStock: true,
    aliases: ["tel", "oil"],
    keywords: ["grocery", "cooking", "daily"],
    popularityScore: 96,
  },
  {
    businessType: "mini_grocery",
    name: "Sugar",
    brand: "Pran",
    category: "Staples",
    packSize: "1kg",
    defaultSellPrice: 140,
    defaultBarcode: "2800000000100",
    defaultBaseUnit: "kg",
    defaultTrackStock: true,
    aliases: ["chini", "sugar"],
    keywords: ["grocery", "staple", "daily"],
    popularityScore: 92,
  },
  {
    businessType: "mini_grocery",
    name: "Red Lentil",
    brand: "Teer",
    category: "Staples",
    packSize: "1kg",
    defaultSellPrice: 160,
    defaultBarcode: "2800000000117",
    defaultBaseUnit: "kg",
    defaultTrackStock: true,
    aliases: ["mosur dal", "dal"],
    keywords: ["grocery", "staple", "daily"],
    popularityScore: 90,
  },
  {
    businessType: "mini_grocery",
    name: "Iodized Salt",
    brand: "Molla",
    category: "Staples",
    packSize: "1kg",
    defaultSellPrice: 45,
    defaultBarcode: "2800000000124",
    defaultBaseUnit: "kg",
    defaultTrackStock: true,
    aliases: ["lobon", "salt"],
    keywords: ["grocery", "daily"],
    popularityScore: 88,
  },
  {
    businessType: "mini_grocery",
    name: "Eggs",
    category: "Dairy",
    packSize: "12 pcs",
    defaultSellPrice: 160,
    defaultBaseUnit: "pcs",
    defaultTrackStock: true,
    aliases: ["dim", "eggs dozen"],
    keywords: ["grocery", "protein", "daily"],
    popularityScore: 86,
  },
  {
    businessType: "clothing",
    name: "Basic T-Shirt",
    brand: "Generic",
    category: "Mens Wear",
    defaultSellPrice: 350,
    aliases: ["tshirt", "tee"],
    keywords: ["fashion", "casual", "apparel"],
    variants: [
      { label: "M", sellPrice: 350, sortOrder: 0 },
      { label: "L", sellPrice: 350, sortOrder: 1 },
      { label: "XL", sellPrice: 380, sortOrder: 2 },
    ],
    popularityScore: 90,
  },
  {
    businessType: "clothing",
    name: "Formal Shirt",
    brand: "Generic",
    category: "Mens Wear",
    defaultSellPrice: 850,
    aliases: ["shirt"],
    keywords: ["fashion", "office", "apparel"],
    variants: [
      { label: "M", sellPrice: 850, sortOrder: 0 },
      { label: "L", sellPrice: 850, sortOrder: 1 },
      { label: "XL", sellPrice: 900, sortOrder: 2 },
    ],
    popularityScore: 84,
  },
  {
    businessType: "clothing",
    name: "Jeans Pant",
    brand: "Generic",
    category: "Bottom Wear",
    defaultSellPrice: 1200,
    aliases: ["jeans"],
    keywords: ["fashion", "denim", "apparel"],
    variants: [
      { label: "30", sellPrice: 1200, sortOrder: 0 },
      { label: "32", sellPrice: 1200, sortOrder: 1 },
      { label: "34", sellPrice: 1250, sortOrder: 2 },
    ],
    popularityScore: 78,
  },
  {
    businessType: "cosmetics_gift",
    name: "Beauty Soap",
    brand: "Lux",
    category: "Personal Care",
    packSize: "100g",
    defaultSellPrice: 65,
    defaultBarcode: "2800000000131",
    aliases: ["soap"],
    keywords: ["cosmetics", "daily care"],
    popularityScore: 88,
  },
  {
    businessType: "cosmetics_gift",
    name: "Shampoo Bottle",
    brand: "Sunsilk",
    category: "Hair Care",
    packSize: "170ml",
    defaultSellPrice: 210,
    defaultBarcode: "2800000000148",
    aliases: ["shampoo"],
    keywords: ["cosmetics", "hair care"],
    popularityScore: 84,
  },
  {
    businessType: "cosmetics_gift",
    name: "Face Wash",
    brand: "Ponds",
    category: "Skin Care",
    packSize: "100g",
    defaultSellPrice: 180,
    defaultBarcode: "2800000000155",
    aliases: ["facewash"],
    keywords: ["cosmetics", "skin care"],
    popularityScore: 72,
  },
  {
    businessType: "pharmacy",
    name: "Napa Tablet",
    brand: "Beximco",
    category: "Medicine",
    packSize: "10 tablets",
    defaultSellPrice: 12,
    defaultBarcode: "2800000000162",
    defaultBaseUnit: "strip",
    defaultTrackStock: true,
    aliases: ["paracetamol", "napa"],
    keywords: ["pharmacy", "pain", "medicine"],
    popularityScore: 98,
  },
  {
    businessType: "pharmacy",
    name: "Seclo 20mg",
    brand: "Square",
    category: "Medicine",
    packSize: "10 capsules",
    defaultSellPrice: 70,
    defaultBarcode: "2800000000179",
    defaultBaseUnit: "strip",
    defaultTrackStock: true,
    aliases: ["gas medicine", "seclo"],
    keywords: ["pharmacy", "medicine"],
    popularityScore: 80,
  },
  {
    businessType: "pharmacy",
    name: "ORS Sachet",
    brand: "Orsaline-N",
    category: "Medicine",
    packSize: "1 sachet",
    defaultSellPrice: 8,
    defaultBarcode: "2800000000186",
    defaultBaseUnit: "pcs",
    defaultTrackStock: true,
    aliases: ["saline", "ors"],
    keywords: ["pharmacy", "hydration"],
    popularityScore: 86,
  },
  {
    businessType: "pharmacy",
    name: "Savlon Liquid",
    brand: "ACI",
    category: "First Aid",
    packSize: "125ml",
    defaultSellPrice: 90,
    defaultBarcode: "2800000000193",
    defaultBaseUnit: "ml",
    defaultTrackStock: true,
    aliases: ["savlon"],
    keywords: ["pharmacy", "antiseptic", "first aid"],
    popularityScore: 74,
  },
  {
    businessType: "mini_wholesale",
    name: "Miniket Rice Sack",
    brand: "ACI",
    category: "Staples",
    packSize: "25kg",
    defaultSellPrice: 2050,
    defaultBarcode: "2800000000209",
    defaultBaseUnit: "carton",
    defaultTrackStock: true,
    aliases: ["rice sack", "chal bosta"],
    keywords: ["wholesale", "bulk", "staple"],
    popularityScore: 94,
  },
  {
    businessType: "mini_wholesale",
    name: "Soybean Oil Carton",
    brand: "Fresh",
    category: "Oil",
    packSize: "5L x 4",
    defaultSellPrice: 3500,
    defaultBarcode: "2800000000216",
    defaultBaseUnit: "carton",
    defaultTrackStock: true,
    aliases: ["oil carton"],
    keywords: ["wholesale", "bulk", "grocery"],
    popularityScore: 88,
  },
  {
    businessType: "mini_wholesale",
    name: "Biscuit Carton",
    brand: "Olympic",
    category: "Snacks",
    packSize: "24 packs",
    defaultSellPrice: 780,
    defaultBarcode: "2800000000223",
    defaultBaseUnit: "box",
    defaultTrackStock: true,
    aliases: ["biscuit box"],
    keywords: ["wholesale", "snacks", "bulk"],
    popularityScore: 76,
  },

  // ── Hardware / সিমেন্ট / ফিটিংস ──
  {
    businessType: "hardware",
    name: "সিমেন্ট (Shah/Crown)",
    category: "সিমেন্ট/বিল্ডিং",
    packSize: "50kg bag",
    defaultSellPrice: 480,
    defaultBaseUnit: "bag",
    defaultTrackStock: true,
    aliases: ["cement", "সিমেন্ট ব্যাগ"],
    keywords: ["cement", "building", "construction"],
    popularityScore: 98,
  },
  {
    businessType: "hardware",
    name: "রড 60 গ্রেড",
    category: "সিমেন্ট/বিল্ডিং",
    defaultSellPrice: 85,
    defaultBaseUnit: "kg",
    defaultTrackStock: true,
    aliases: ["rod", "iron rod", "রড"],
    keywords: ["rod", "construction", "building"],
    popularityScore: 95,
    variants: [
      { label: "8mm", sellPrice: 75, sortOrder: 0 },
      { label: "10mm", sellPrice: 85, sortOrder: 1 },
      { label: "12mm", sellPrice: 90, sortOrder: 2 },
      { label: "16mm", sellPrice: 95, sortOrder: 3 },
      { label: "20mm", sellPrice: 100, sortOrder: 4 },
    ],
  },
  {
    businessType: "hardware",
    name: "PVC পাইপ",
    category: "পাইপ/ফিটিংস",
    defaultSellPrice: 35,
    defaultBaseUnit: "ft",
    defaultTrackStock: true,
    aliases: ["pipe", "পাইপ", "pvc pipe"],
    keywords: ["pipe", "plumbing", "fitting"],
    popularityScore: 90,
    variants: [
      { label: "1/2\" (প্রতি ফুট)", sellPrice: 22, sortOrder: 0 },
      { label: "3/4\" (প্রতি ফুট)", sellPrice: 35, sortOrder: 1 },
      { label: "1\" (প্রতি ফুট)", sellPrice: 52, sortOrder: 2 },
      { label: "1.5\" (প্রতি ফুট)", sellPrice: 80, sortOrder: 3 },
      { label: "2\" (প্রতি ফুট)", sellPrice: 120, sortOrder: 4 },
    ],
  },
  {
    businessType: "hardware",
    name: "ইলেকট্রিক তার",
    category: "ইলেকট্রিক্যাল",
    defaultSellPrice: 450,
    defaultBaseUnit: "coil",
    defaultTrackStock: true,
    aliases: ["wire", "তার", "electric wire"],
    keywords: ["wire", "electric", "cable"],
    popularityScore: 88,
    variants: [
      { label: "1.5mm² (100ft coil)", sellPrice: 380, sortOrder: 0 },
      { label: "2.5mm² (100ft coil)", sellPrice: 560, sortOrder: 1 },
      { label: "4mm² (100ft coil)", sellPrice: 850, sortOrder: 2 },
      { label: "6mm² (100ft coil)", sellPrice: 1200, sortOrder: 3 },
    ],
  },
  {
    businessType: "hardware",
    name: "পেরেক (নেইল)",
    category: "হার্ডওয়্যার",
    defaultSellPrice: 120,
    defaultBaseUnit: "kg",
    defaultTrackStock: true,
    aliases: ["nail", "পেরেক"],
    keywords: ["nail", "hardware", "fastener"],
    popularityScore: 85,
    variants: [
      { label: "1.5\" (প্রতি কেজি)", sellPrice: 110, sortOrder: 0 },
      { label: "2\" (প্রতি কেজি)", sellPrice: 115, sortOrder: 1 },
      { label: "3\" (প্রতি কেজি)", sellPrice: 120, sortOrder: 2 },
      { label: "4\" (প্রতি কেজি)", sellPrice: 130, sortOrder: 3 },
    ],
  },
  {
    businessType: "hardware",
    name: "স্ক্রু বক্স",
    category: "হার্ডওয়্যার",
    defaultSellPrice: 60,
    defaultBaseUnit: "box",
    defaultTrackStock: true,
    aliases: ["screw", "স্ক্রু"],
    keywords: ["screw", "hardware", "fastener"],
    popularityScore: 82,
  },
  {
    businessType: "hardware",
    name: "ইট",
    category: "সিমেন্ট/বিল্ডিং",
    defaultSellPrice: 12,
    defaultBaseUnit: "pcs",
    defaultTrackStock: true,
    aliases: ["brick", "ইটা"],
    keywords: ["brick", "building", "construction"],
    popularityScore: 80,
  },
  {
    businessType: "hardware",
    name: "রং (পেইন্ট)",
    category: "রং/কেমিক্যাল",
    defaultSellPrice: 350,
    defaultBaseUnit: "liter",
    defaultTrackStock: true,
    aliases: ["paint", "রং", "colour"],
    keywords: ["paint", "color", "finishing"],
    popularityScore: 78,
    variants: [
      { label: "1 লিটার", sellPrice: 350, sortOrder: 0 },
      { label: "4 লিটার", sellPrice: 1300, sortOrder: 1 },
      { label: "10 লিটার", sellPrice: 3100, sortOrder: 2 },
      { label: "20 লিটার", sellPrice: 5800, sortOrder: 3 },
    ],
  },
  {
    businessType: "hardware",
    name: "টাইলস",
    category: "সিমেন্ট/বিল্ডিং",
    defaultSellPrice: 55,
    defaultBaseUnit: "pcs",
    defaultTrackStock: true,
    aliases: ["tiles", "টাইল"],
    keywords: ["tiles", "floor", "wall", "building"],
    popularityScore: 75,
    variants: [
      { label: "12\"×12\"", sellPrice: 38, sortOrder: 0 },
      { label: "18\"×18\"", sellPrice: 55, sortOrder: 1 },
      { label: "24\"×24\"", sellPrice: 95, sortOrder: 2 },
      { label: "12\"×24\"", sellPrice: 75, sortOrder: 3 },
    ],
  },
  {
    businessType: "hardware",
    name: "সুইচ/সকেট",
    category: "ইলেকট্রিক্যাল",
    defaultSellPrice: 45,
    defaultBaseUnit: "pcs",
    defaultTrackStock: true,
    aliases: ["switch", "socket", "সুইচ"],
    keywords: ["switch", "socket", "electric"],
    popularityScore: 72,
  },

  // ── Hardware extra products ──
  {
    businessType: "hardware",
    name: "বালু",
    category: "বালু/খোয়া",
    defaultSellPrice: 60,
    defaultBaseUnit: "cft",
    defaultTrackStock: true,
    aliases: ["sand", "বালি"],
    keywords: ["sand", "building", "construction"],
    popularityScore: 88,
  },
  {
    businessType: "hardware",
    name: "খোয়া / পাথর",
    category: "বালু/খোয়া",
    defaultSellPrice: 90,
    defaultBaseUnit: "cft",
    defaultTrackStock: true,
    aliases: ["khoa", "stone chips", "aggregate"],
    keywords: ["stone", "aggregate", "building", "construction"],
    popularityScore: 85,
  },
  {
    businessType: "hardware",
    name: "ঢেউটিন (GI শিট)",
    category: "ছাদ/শিট",
    defaultSellPrice: 1100,
    defaultBaseUnit: "pcs",
    defaultTrackStock: true,
    aliases: ["tin sheet", "gi sheet", "dhewotin", "ঢেউ টিন"],
    keywords: ["tin", "roof", "sheet", "gi"],
    popularityScore: 86,
    variants: [
      { label: "8 ফুট", sellPrice: 850, sortOrder: 0 },
      { label: "10 ফুট", sellPrice: 1100, sortOrder: 1 },
      { label: "12 ফুট", sellPrice: 1320, sortOrder: 2 },
      { label: "14 ফুট", sellPrice: 1540, sortOrder: 3 },
    ],
  },
  {
    businessType: "hardware",
    name: "রড বাঁধার তার (বাইন্ডিং ওয়্যার)",
    category: "সিমেন্ট/বিল্ডিং",
    defaultSellPrice: 130,
    defaultBaseUnit: "kg",
    defaultTrackStock: true,
    aliases: ["binding wire", "তার", "rod wire"],
    keywords: ["wire", "binding", "construction", "rod"],
    popularityScore: 84,
  },
  {
    businessType: "hardware",
    name: "এঙ্গেল আয়রন",
    category: "স্ট্রাকচারাল",
    defaultSellPrice: 110,
    defaultBaseUnit: "kg",
    defaultTrackStock: true,
    aliases: ["angle iron", "angle bar", "এঙ্গেল"],
    keywords: ["angle", "iron", "structural", "steel"],
    popularityScore: 82,
    variants: [
      { label: "1\"×1\" (10ft)", sellPrice: 320, sortOrder: 0 },
      { label: "1.5\"×1.5\" (10ft)", sellPrice: 520, sortOrder: 1 },
      { label: "2\"×2\" (10ft)", sellPrice: 750, sortOrder: 2 },
    ],
  },
  {
    businessType: "hardware",
    name: "MS চ্যানেল",
    category: "স্ট্রাকচারাল",
    defaultSellPrice: 160,
    defaultBaseUnit: "kg",
    defaultTrackStock: true,
    aliases: ["channel", "ms channel", "চ্যানেল"],
    keywords: ["channel", "steel", "structural"],
    popularityScore: 72,
    variants: [
      { label: "3\"×1.5\" (10ft)", sellPrice: 980, sortOrder: 0 },
      { label: "4\"×2\" (10ft)", sellPrice: 1450, sortOrder: 1 },
    ],
  },
  {
    businessType: "hardware",
    name: "PVC এলবো",
    category: "পাইপ/ফিটিংস",
    defaultSellPrice: 18,
    defaultBaseUnit: "pcs",
    defaultTrackStock: true,
    aliases: ["elbow", "এলবো", "pvc elbow"],
    keywords: ["elbow", "fitting", "pipe", "plumbing"],
    popularityScore: 80,
    variants: [
      { label: "1/2\"", sellPrice: 12, sortOrder: 0 },
      { label: "3/4\"", sellPrice: 18, sortOrder: 1 },
      { label: "1\"", sellPrice: 28, sortOrder: 2 },
      { label: "1.5\"", sellPrice: 45, sortOrder: 3 },
    ],
  },
  {
    businessType: "hardware",
    name: "PVC টি (Tee)",
    category: "পাইপ/ফিটিংস",
    defaultSellPrice: 20,
    defaultBaseUnit: "pcs",
    defaultTrackStock: true,
    aliases: ["tee", "টি", "pvc tee"],
    keywords: ["tee", "fitting", "pipe", "plumbing"],
    popularityScore: 76,
    variants: [
      { label: "1/2\"", sellPrice: 14, sortOrder: 0 },
      { label: "3/4\"", sellPrice: 20, sortOrder: 1 },
      { label: "1\"", sellPrice: 32, sortOrder: 2 },
    ],
  },
  {
    businessType: "hardware",
    name: "বল ভাল্ব",
    category: "পাইপ/ফিটিংস",
    defaultSellPrice: 120,
    defaultBaseUnit: "pcs",
    defaultTrackStock: true,
    aliases: ["ball valve", "valve", "ভাল্ব", "কল"],
    keywords: ["valve", "ball valve", "fitting", "plumbing"],
    popularityScore: 78,
    variants: [
      { label: "1/2\"", sellPrice: 80, sortOrder: 0 },
      { label: "3/4\"", sellPrice: 120, sortOrder: 1 },
      { label: "1\"", sellPrice: 180, sortOrder: 2 },
      { label: "1.5\"", sellPrice: 280, sortOrder: 3 },
    ],
  },
  {
    businessType: "hardware",
    name: "ওয়াটার ট্যাংক",
    category: "পাইপ/ফিটিংস",
    defaultSellPrice: 3500,
    defaultBaseUnit: "pcs",
    defaultTrackStock: true,
    aliases: ["water tank", "ট্যাংক", "পানির ট্যাংক"],
    keywords: ["tank", "water", "storage"],
    popularityScore: 74,
    variants: [
      { label: "500 লিটার", sellPrice: 2800, sortOrder: 0 },
      { label: "1000 লিটার", sellPrice: 4500, sortOrder: 1 },
      { label: "2000 লিটার", sellPrice: 8200, sortOrder: 2 },
    ],
  },
  {
    businessType: "hardware",
    name: "MS পাইপ",
    category: "পাইপ/ফিটিংস",
    defaultSellPrice: 420,
    defaultBaseUnit: "pcs",
    defaultTrackStock: true,
    aliases: ["ms pipe", "iron pipe", "steel pipe"],
    keywords: ["ms pipe", "pipe", "structural", "plumbing"],
    popularityScore: 76,
    variants: [
      { label: "1/2\" (10ft)", sellPrice: 280, sortOrder: 0 },
      { label: "3/4\" (10ft)", sellPrice: 420, sortOrder: 1 },
      { label: "1\" (10ft)", sellPrice: 620, sortOrder: 2 },
    ],
  },
  {
    businessType: "hardware",
    name: "MCB (সার্কিট ব্রেকার)",
    category: "ইলেকট্রিক্যাল",
    defaultSellPrice: 250,
    defaultBaseUnit: "pcs",
    defaultTrackStock: true,
    aliases: ["mcb", "circuit breaker", "ব্রেকার"],
    keywords: ["mcb", "circuit breaker", "electric", "safety"],
    popularityScore: 78,
    variants: [
      { label: "10 Amp", sellPrice: 200, sortOrder: 0 },
      { label: "16 Amp", sellPrice: 230, sortOrder: 1 },
      { label: "20 Amp", sellPrice: 260, sortOrder: 2 },
      { label: "32 Amp", sellPrice: 320, sortOrder: 3 },
    ],
  },
  {
    businessType: "hardware",
    name: "বাল্ব হোল্ডার",
    category: "ইলেকট্রিক্যাল",
    defaultSellPrice: 30,
    defaultBaseUnit: "pcs",
    defaultTrackStock: true,
    aliases: ["bulb holder", "holder", "হোল্ডার"],
    keywords: ["holder", "bulb", "electric", "light"],
    popularityScore: 70,
  },
  {
    businessType: "hardware",
    name: "ফ্যান রেগুলেটর",
    category: "ইলেকট্রিক্যাল",
    defaultSellPrice: 180,
    defaultBaseUnit: "pcs",
    defaultTrackStock: true,
    aliases: ["fan regulator", "regulator", "রেগুলেটর"],
    keywords: ["fan", "regulator", "electric"],
    popularityScore: 68,
  },
  {
    businessType: "hardware",
    name: "কন্ডুইট পাইপ",
    category: "ইলেকট্রিক্যাল",
    defaultSellPrice: 95,
    defaultBaseUnit: "pcs",
    defaultTrackStock: true,
    aliases: ["conduit", "conduit pipe", "ক্যাবল পাইপ"],
    keywords: ["conduit", "pipe", "electric", "wiring"],
    popularityScore: 66,
    variants: [
      { label: "3/4\" (10ft)", sellPrice: 75, sortOrder: 0 },
      { label: "1\" (10ft)", sellPrice: 95, sortOrder: 1 },
    ],
  },
  {
    businessType: "hardware",
    name: "থিনার",
    category: "রং/কেমিক্যাল",
    defaultSellPrice: 220,
    defaultBaseUnit: "liter",
    defaultTrackStock: true,
    aliases: ["thinner", "paint thinner"],
    keywords: ["thinner", "paint", "chemical"],
    popularityScore: 74,
    variants: [
      { label: "1 লিটার", sellPrice: 220, sortOrder: 0 },
      { label: "4 লিটার", sellPrice: 800, sortOrder: 1 },
    ],
  },
  {
    businessType: "hardware",
    name: "পুটি",
    category: "রং/কেমিক্যাল",
    defaultSellPrice: 180,
    defaultBaseUnit: "kg",
    defaultTrackStock: true,
    aliases: ["putty", "wall putty"],
    keywords: ["putty", "paint", "wall", "finishing"],
    popularityScore: 72,
    variants: [
      { label: "1 কেজি", sellPrice: 180, sortOrder: 0 },
      { label: "5 কেজি", sellPrice: 820, sortOrder: 1 },
      { label: "20 কেজি (বস্তা)", sellPrice: 3000, sortOrder: 2 },
    ],
  },
  {
    businessType: "hardware",
    name: "প্রাইমার",
    category: "রং/কেমিক্যাল",
    defaultSellPrice: 280,
    defaultBaseUnit: "liter",
    defaultTrackStock: true,
    aliases: ["primer", "paint primer"],
    keywords: ["primer", "paint", "undercoat"],
    popularityScore: 68,
    variants: [
      { label: "1 লিটার", sellPrice: 280, sortOrder: 0 },
      { label: "4 লিটার", sellPrice: 1050, sortOrder: 1 },
    ],
  },
  {
    businessType: "hardware",
    name: "বার্নিশ",
    category: "রং/কেমিক্যাল",
    defaultSellPrice: 320,
    defaultBaseUnit: "liter",
    defaultTrackStock: true,
    aliases: ["varnish", "wood varnish"],
    keywords: ["varnish", "wood", "finish"],
    popularityScore: 64,
    variants: [
      { label: "1 লিটার", sellPrice: 320, sortOrder: 0 },
      { label: "4 লিটার", sellPrice: 1200, sortOrder: 1 },
    ],
  },
  {
    businessType: "hardware",
    name: "দরজার লক (পাড়া)",
    category: "হার্ডওয়্যার",
    defaultSellPrice: 350,
    defaultBaseUnit: "pcs",
    defaultTrackStock: true,
    aliases: ["door lock", "lock", "তালা", "মর্টাইজ"],
    keywords: ["lock", "door", "hardware", "security"],
    popularityScore: 76,
    variants: [
      { label: "ছোট (2\")", sellPrice: 220, sortOrder: 0 },
      { label: "মাঝারি (3\")", sellPrice: 350, sortOrder: 1 },
      { label: "বড় (4\")", sellPrice: 520, sortOrder: 2 },
    ],
  },
  {
    businessType: "hardware",
    name: "হিঞ্জ (কব্জা)",
    category: "হার্ডওয়্যার",
    defaultSellPrice: 80,
    defaultBaseUnit: "pcs",
    defaultTrackStock: true,
    aliases: ["hinge", "kobja", "কব্জা"],
    keywords: ["hinge", "door", "hardware"],
    popularityScore: 74,
    variants: [
      { label: "3 ইঞ্চি (জোড়া)", sellPrice: 60, sortOrder: 0 },
      { label: "4 ইঞ্চি (জোড়া)", sellPrice: 80, sortOrder: 1 },
      { label: "5 ইঞ্চি (জোড়া)", sellPrice: 110, sortOrder: 2 },
    ],
  },
  {
    businessType: "hardware",
    name: "নাট-বোল্ট",
    category: "হার্ডওয়্যার",
    defaultSellPrice: 5,
    defaultBaseUnit: "pcs",
    defaultTrackStock: true,
    aliases: ["nut bolt", "bolt", "নাট বোল্ট"],
    keywords: ["nut", "bolt", "fastener", "hardware"],
    popularityScore: 80,
    variants: [
      { label: "M8×50mm", sellPrice: 5, sortOrder: 0 },
      { label: "M10×50mm", sellPrice: 8, sortOrder: 1 },
      { label: "M12×75mm", sellPrice: 12, sortOrder: 2 },
    ],
  },
  {
    businessType: "hardware",
    name: "দরজার হ্যান্ডেল",
    category: "হার্ডওয়্যার",
    defaultSellPrice: 180,
    defaultBaseUnit: "pcs",
    defaultTrackStock: true,
    aliases: ["handle", "door handle", "হ্যান্ডেল"],
    keywords: ["handle", "door", "hardware"],
    popularityScore: 70,
    variants: [
      { label: "সাধারণ", sellPrice: 120, sortOrder: 0 },
      { label: "স্টিল", sellPrice: 180, sortOrder: 1 },
      { label: "প্রিমিয়াম", sellPrice: 320, sortOrder: 2 },
    ],
  },
  {
    businessType: "hardware",
    name: "প্লাইউড / বোর্ড",
    category: "কাঠ/বোর্ড",
    defaultSellPrice: 2200,
    defaultBaseUnit: "pcs",
    defaultTrackStock: true,
    aliases: ["plywood", "board", "প্লাই"],
    keywords: ["plywood", "wood", "board", "furniture"],
    popularityScore: 70,
    variants: [
      { label: "4mm (4×8ft)", sellPrice: 1200, sortOrder: 0 },
      { label: "6mm (4×8ft)", sellPrice: 1600, sortOrder: 1 },
      { label: "12mm (4×8ft)", sellPrice: 2800, sortOrder: 2 },
      { label: "18mm (4×8ft)", sellPrice: 3800, sortOrder: 3 },
    ],
  },
  {
    businessType: "hardware",
    name: "সিলিকন সিলান্ট",
    category: "রং/কেমিক্যাল",
    defaultSellPrice: 250,
    defaultBaseUnit: "pcs",
    defaultTrackStock: true,
    aliases: ["silicone", "sealant", "সিলান্ট"],
    keywords: ["silicone", "sealant", "waterproof"],
    popularityScore: 66,
  },
  {
    businessType: "hardware",
    name: "ফেভিকল / কাঠ আঠা",
    category: "রং/কেমিক্যাল",
    defaultSellPrice: 180,
    defaultBaseUnit: "pcs",
    defaultTrackStock: true,
    aliases: ["fevicol", "adhesive", "glue", "আঠা"],
    keywords: ["adhesive", "glue", "wood", "chemical"],
    popularityScore: 68,
    variants: [
      { label: "200g", sellPrice: 90, sortOrder: 0 },
      { label: "500g", sellPrice: 200, sortOrder: 1 },
      { label: "1kg", sellPrice: 370, sortOrder: 2 },
    ],
  },
  {
    businessType: "hardware",
    name: "GI তার",
    category: "হার্ডওয়্যার",
    defaultSellPrice: 145,
    defaultBaseUnit: "kg",
    defaultTrackStock: true,
    aliases: ["gi wire", "galvanized wire", "জিআই তার"],
    keywords: ["gi wire", "wire", "hardware"],
    popularityScore: 72,
    variants: [
      { label: "16 গেজ", sellPrice: 145, sortOrder: 0 },
      { label: "18 গেজ", sellPrice: 155, sortOrder: 1 },
      { label: "20 গেজ", sellPrice: 165, sortOrder: 2 },
    ],
  },
  {
    businessType: "hardware",
    name: "হ্যাসপ / আলনা ছিটকানি",
    category: "হার্ডওয়্যার",
    defaultSellPrice: 35,
    defaultBaseUnit: "pcs",
    defaultTrackStock: true,
    aliases: ["hasp", "latch", "bolt", "ছিটকানি"],
    keywords: ["hasp", "latch", "door", "hardware"],
    popularityScore: 65,
    variants: [
      { label: "ছোট", sellPrice: 25, sortOrder: 0 },
      { label: "মাঝারি", sellPrice: 35, sortOrder: 1 },
      { label: "বড়", sellPrice: 55, sortOrder: 2 },
    ],
  },
  {
    businessType: "hardware",
    name: "মেশিন অয়েল / লুব্রিকেন্ট",
    category: "হার্ডওয়্যার",
    defaultSellPrice: 180,
    defaultBaseUnit: "liter",
    defaultTrackStock: true,
    aliases: ["machine oil", "lubricant", "oil", "তেল"],
    keywords: ["oil", "lubricant", "machine", "maintenance"],
    popularityScore: 62,
    variants: [
      { label: "500ml", sellPrice: 110, sortOrder: 0 },
      { label: "1 লিটার", sellPrice: 180, sortOrder: 1 },
    ],
  },
  {
    businessType: "hardware",
    name: "পানির পাম্প",
    category: "পাইপ/ফিটিংস",
    defaultSellPrice: 4500,
    defaultBaseUnit: "pcs",
    defaultTrackStock: true,
    aliases: ["water pump", "pump", "পাম্প"],
    keywords: ["pump", "water", "motor", "electric"],
    popularityScore: 68,
    variants: [
      { label: "0.5 HP", sellPrice: 3200, sortOrder: 0 },
      { label: "1 HP", sellPrice: 4500, sortOrder: 1 },
      { label: "1.5 HP", sellPrice: 6500, sortOrder: 2 },
      { label: "2 HP", sellPrice: 8500, sortOrder: 3 },
    ],
  },
  {
    businessType: "hardware",
    name: "গ্রিল / জাফরি",
    category: "স্ট্রাকচারাল",
    defaultSellPrice: 180,
    defaultBaseUnit: "sqft",
    defaultTrackStock: true,
    aliases: ["grill", "grille", "jafri", "গ্রিল"],
    keywords: ["grill", "window", "door", "structural", "iron"],
    popularityScore: 66,
  },
  {
    businessType: "hardware",
    name: "মেজারিং টেপ",
    category: "হার্ডওয়্যার",
    defaultSellPrice: 150,
    defaultBaseUnit: "pcs",
    defaultTrackStock: true,
    aliases: ["measuring tape", "tape", "ফিতা"],
    keywords: ["tape", "measure", "tool", "hardware"],
    popularityScore: 60,
    variants: [
      { label: "5 মিটার", sellPrice: 80, sortOrder: 0 },
      { label: "10 মিটার", sellPrice: 150, sortOrder: 1 },
      { label: "30 মিটার", sellPrice: 350, sortOrder: 2 },
    ],
  },
];
