export type StarterTemplateVariant = {
  label: string;
  sellPrice: number;
  sku?: string | null;
  barcode?: string | null;
  sortOrder?: number;
  isActive?: boolean;
};

export type StarterBusinessProductTemplate = {
  businessType: string;
  name: string;
  brand?: string | null;
  category?: string | null;
  packSize?: string | null;
  defaultSellPrice?: number | null;
  defaultBarcode?: string | null;
  defaultBaseUnit?: string | null;
  defaultTrackStock?: boolean;
  aliases?: string[];
  keywords?: string[];
  variants?: StarterTemplateVariant[];
  imageUrl?: string | null;
  popularityScore?: number;
  isActive?: boolean;
};

export const STARTER_BUSINESS_PRODUCT_TEMPLATES: StarterBusinessProductTemplate[] = [
  {
    businessType: "tea_stall",
    name: "Milk Tea",
    category: "Beverages",
    defaultSellPrice: 25,
    aliases: ["dudh cha", "tea"],
    keywords: ["tea", "hot", "drink"],
    popularityScore: 98,
  },
  {
    businessType: "tea_stall",
    name: "Black Tea",
    category: "Beverages",
    defaultSellPrice: 20,
    aliases: ["rong cha", "black tea"],
    keywords: ["tea", "hot", "drink"],
    popularityScore: 92,
  },
  {
    businessType: "tea_stall",
    name: "Coffee",
    category: "Beverages",
    defaultSellPrice: 40,
    aliases: ["black coffee", "hot coffee"],
    keywords: ["coffee", "drink"],
    popularityScore: 86,
  },
  {
    businessType: "tea_stall",
    name: "Lemon Tea",
    category: "Beverages",
    defaultSellPrice: 30,
    aliases: ["lebu tea", "lemon cha"],
    keywords: ["tea", "lemon", "drink"],
    popularityScore: 78,
  },
  {
    businessType: "tea_stall",
    name: "Toast Biscuit",
    brand: "Olympic",
    category: "Snacks",
    packSize: "1 pack",
    defaultSellPrice: 10,
    defaultBarcode: "2800000000001",
    aliases: ["biscuit", "toast"],
    keywords: ["snacks", "tea stall", "biscuit"],
    popularityScore: 72,
  },
  {
    businessType: "pan_cigarette",
    name: "Gold Leaf Regular",
    brand: "Gold Leaf",
    category: "Cigarette",
    packSize: "10 sticks",
    defaultSellPrice: 20,
    defaultBarcode: "2800000000018",
    aliases: ["goldleaf", "gl regular"],
    keywords: ["cigarette", "smoke"],
    popularityScore: 96,
  },
  {
    businessType: "pan_cigarette",
    name: "Benson Switch",
    brand: "Benson",
    category: "Cigarette",
    packSize: "10 sticks",
    defaultSellPrice: 23,
    defaultBarcode: "2800000000025",
    aliases: ["benson", "switch"],
    keywords: ["cigarette", "smoke"],
    popularityScore: 90,
  },
  {
    businessType: "pan_cigarette",
    name: "Navy Cigarette",
    brand: "Navy",
    category: "Cigarette",
    packSize: "10 sticks",
    defaultSellPrice: 18,
    defaultBarcode: "2800000000032",
    aliases: ["navy"],
    keywords: ["cigarette", "smoke"],
    popularityScore: 82,
  },
  {
    businessType: "pan_cigarette",
    name: "Jarda Paan",
    category: "Paan",
    defaultSellPrice: 15,
    aliases: ["paan", "jorda pan"],
    keywords: ["paan", "betel"],
    popularityScore: 70,
  },
  {
    businessType: "pan_cigarette",
    name: "Mineral Water",
    brand: "Mum",
    category: "Drinks",
    packSize: "500ml",
    defaultSellPrice: 20,
    defaultBarcode: "2800000000049",
    aliases: ["water", "bottled water"],
    keywords: ["drink", "water"],
    popularityScore: 74,
  },
  {
    businessType: "mobile_recharge",
    name: "Grameenphone Flexiload",
    brand: "Grameenphone",
    category: "Recharge",
    defaultSellPrice: 20,
    aliases: ["gp recharge", "gp flexi"],
    keywords: ["mobile", "recharge", "topup"],
    popularityScore: 95,
  },
  {
    businessType: "mobile_recharge",
    name: "Robi Flexiload",
    brand: "Robi",
    category: "Recharge",
    defaultSellPrice: 20,
    aliases: ["robi recharge", "robi flexi"],
    keywords: ["mobile", "recharge", "topup"],
    popularityScore: 90,
  },
  {
    businessType: "mobile_recharge",
    name: "Banglalink Flexiload",
    brand: "Banglalink",
    category: "Recharge",
    defaultSellPrice: 20,
    aliases: ["bl recharge", "banglalink flexi"],
    keywords: ["mobile", "recharge", "topup"],
    popularityScore: 88,
  },
  {
    businessType: "mobile_recharge",
    name: "Airtel Flexiload",
    brand: "Airtel",
    category: "Recharge",
    defaultSellPrice: 20,
    aliases: ["airtel recharge"],
    keywords: ["mobile", "recharge", "topup"],
    popularityScore: 74,
  },
  {
    businessType: "mobile_recharge",
    name: "Teletalk Flexiload",
    brand: "Teletalk",
    category: "Recharge",
    defaultSellPrice: 20,
    aliases: ["tt recharge", "teletalk recharge"],
    keywords: ["mobile", "recharge", "topup"],
    popularityScore: 58,
  },
  {
    businessType: "fruits_veg",
    name: "Potato",
    category: "Vegetables",
    defaultSellPrice: 60,
    defaultBaseUnit: "kg",
    defaultTrackStock: true,
    aliases: ["alu"],
    keywords: ["vegetable", "fresh"],
    popularityScore: 96,
  },
  {
    businessType: "fruits_veg",
    name: "Onion",
    category: "Vegetables",
    defaultSellPrice: 90,
    defaultBaseUnit: "kg",
    defaultTrackStock: true,
    aliases: ["peyaj"],
    keywords: ["vegetable", "fresh"],
    popularityScore: 94,
  },
  {
    businessType: "fruits_veg",
    name: "Tomato",
    category: "Vegetables",
    defaultSellPrice: 80,
    defaultBaseUnit: "kg",
    defaultTrackStock: true,
    aliases: ["tomato"],
    keywords: ["vegetable", "fresh"],
    popularityScore: 88,
  },
  {
    businessType: "fruits_veg",
    name: "Green Chili",
    category: "Vegetables",
    defaultSellPrice: 120,
    defaultBaseUnit: "kg",
    defaultTrackStock: true,
    aliases: ["kancha morich"],
    keywords: ["vegetable", "fresh"],
    popularityScore: 80,
  },
  {
    businessType: "fruits_veg",
    name: "Banana",
    category: "Fruits",
    defaultSellPrice: 12,
    defaultBaseUnit: "pcs",
    defaultTrackStock: true,
    aliases: ["kola"],
    keywords: ["fruit", "fresh"],
    popularityScore: 84,
  },
  {
    businessType: "snacks_stationery",
    name: "Potato Chips",
    brand: "Lays",
    category: "Snacks",
    packSize: "25g",
    defaultSellPrice: 20,
    defaultBarcode: "2800000000056",
    aliases: ["chips"],
    keywords: ["snacks", "packet"],
    popularityScore: 90,
  },
  {
    businessType: "snacks_stationery",
    name: "Chanachur Pack",
    brand: "Pran",
    category: "Snacks",
    packSize: "35g",
    defaultSellPrice: 15,
    defaultBarcode: "2800000000063",
    aliases: ["chanachur"],
    keywords: ["snacks", "packet"],
    popularityScore: 82,
  },
  {
    businessType: "snacks_stationery",
    name: "Ball Pen",
    brand: "Matador",
    category: "Stationery",
    defaultSellPrice: 10,
    aliases: ["pen"],
    keywords: ["stationery", "writing"],
    popularityScore: 88,
  },
  {
    businessType: "snacks_stationery",
    name: "Notebook",
    brand: "Fresh",
    category: "Stationery",
    packSize: "80 pages",
    defaultSellPrice: 35,
    aliases: ["khata"],
    keywords: ["stationery", "copy", "school"],
    popularityScore: 76,
  },
  {
    businessType: "snacks_stationery",
    name: "Chocolate Bar",
    brand: "Dairy Milk",
    category: "Snacks",
    packSize: "24g",
    defaultSellPrice: 50,
    defaultBarcode: "2800000000070",
    aliases: ["chocolate"],
    keywords: ["snacks", "sweet"],
    popularityScore: 74,
  },
  {
    businessType: "mini_grocery",
    name: "Miniket Rice",
    brand: "ACI",
    category: "Staples",
    packSize: "5kg",
    defaultSellPrice: 420,
    defaultBarcode: "2800000000087",
    defaultBaseUnit: "kg",
    defaultTrackStock: true,
    aliases: ["chal", "rice"],
    keywords: ["grocery", "staple", "daily"],
    popularityScore: 98,
  },
  {
    businessType: "mini_grocery",
    name: "Soybean Oil",
    brand: "Fresh",
    category: "Oil",
    packSize: "1L",
    defaultSellPrice: 195,
    defaultBarcode: "2800000000094",
    defaultBaseUnit: "liter",
    defaultTrackStock: true,
    aliases: ["tel", "oil"],
    keywords: ["grocery", "cooking", "daily"],
    popularityScore: 96,
  },
  {
    businessType: "mini_grocery",
    name: "Sugar",
    brand: "Pran",
    category: "Staples",
    packSize: "1kg",
    defaultSellPrice: 140,
    defaultBarcode: "2800000000100",
    defaultBaseUnit: "kg",
    defaultTrackStock: true,
    aliases: ["chini", "sugar"],
    keywords: ["grocery", "staple", "daily"],
    popularityScore: 92,
  },
  {
    businessType: "mini_grocery",
    name: "Red Lentil",
    brand: "Teer",
    category: "Staples",
    packSize: "1kg",
    defaultSellPrice: 160,
    defaultBarcode: "2800000000117",
    defaultBaseUnit: "kg",
    defaultTrackStock: true,
    aliases: ["mosur dal", "dal"],
    keywords: ["grocery", "staple", "daily"],
    popularityScore: 90,
  },
  {
    businessType: "mini_grocery",
    name: "Iodized Salt",
    brand: "Molla",
    category: "Staples",
    packSize: "1kg",
    defaultSellPrice: 45,
    defaultBarcode: "2800000000124",
    defaultBaseUnit: "kg",
    defaultTrackStock: true,
    aliases: ["lobon", "salt"],
    keywords: ["grocery", "daily"],
    popularityScore: 88,
  },
  {
    businessType: "mini_grocery",
    name: "Eggs",
    category: "Dairy",
    packSize: "12 pcs",
    defaultSellPrice: 160,
    defaultBaseUnit: "pcs",
    defaultTrackStock: true,
    aliases: ["dim", "eggs dozen"],
    keywords: ["grocery", "protein", "daily"],
    popularityScore: 86,
  },
  {
    businessType: "clothing",
    name: "Basic T-Shirt",
    brand: "Generic",
    category: "Mens Wear",
    defaultSellPrice: 350,
    aliases: ["tshirt", "tee"],
    keywords: ["fashion", "casual", "apparel"],
    variants: [
      { label: "M", sellPrice: 350, sortOrder: 0 },
      { label: "L", sellPrice: 350, sortOrder: 1 },
      { label: "XL", sellPrice: 380, sortOrder: 2 },
    ],
    popularityScore: 90,
  },
  {
    businessType: "clothing",
    name: "Formal Shirt",
    brand: "Generic",
    category: "Mens Wear",
    defaultSellPrice: 850,
    aliases: ["shirt"],
    keywords: ["fashion", "office", "apparel"],
    variants: [
      { label: "M", sellPrice: 850, sortOrder: 0 },
      { label: "L", sellPrice: 850, sortOrder: 1 },
      { label: "XL", sellPrice: 900, sortOrder: 2 },
    ],
    popularityScore: 84,
  },
  {
    businessType: "clothing",
    name: "Jeans Pant",
    brand: "Generic",
    category: "Bottom Wear",
    defaultSellPrice: 1200,
    aliases: ["jeans"],
    keywords: ["fashion", "denim", "apparel"],
    variants: [
      { label: "30", sellPrice: 1200, sortOrder: 0 },
      { label: "32", sellPrice: 1200, sortOrder: 1 },
      { label: "34", sellPrice: 1250, sortOrder: 2 },
    ],
    popularityScore: 78,
  },
  {
    businessType: "cosmetics_gift",
    name: "Beauty Soap",
    brand: "Lux",
    category: "Personal Care",
    packSize: "100g",
    defaultSellPrice: 65,
    defaultBarcode: "2800000000131",
    aliases: ["soap"],
    keywords: ["cosmetics", "daily care"],
    popularityScore: 88,
  },
  {
    businessType: "cosmetics_gift",
    name: "Shampoo Bottle",
    brand: "Sunsilk",
    category: "Hair Care",
    packSize: "170ml",
    defaultSellPrice: 210,
    defaultBarcode: "2800000000148",
    aliases: ["shampoo"],
    keywords: ["cosmetics", "hair care"],
    popularityScore: 84,
  },
  {
    businessType: "cosmetics_gift",
    name: "Face Wash",
    brand: "Ponds",
    category: "Skin Care",
    packSize: "100g",
    defaultSellPrice: 180,
    defaultBarcode: "2800000000155",
    aliases: ["facewash"],
    keywords: ["cosmetics", "skin care"],
    popularityScore: 72,
  },
  {
    businessType: "pharmacy",
    name: "Napa Tablet",
    brand: "Beximco",
    category: "Medicine",
    packSize: "10 tablets",
    defaultSellPrice: 12,
    defaultBarcode: "2800000000162",
    defaultBaseUnit: "strip",
    defaultTrackStock: true,
    aliases: ["paracetamol", "napa"],
    keywords: ["pharmacy", "pain", "medicine"],
    popularityScore: 98,
  },
  {
    businessType: "pharmacy",
    name: "Seclo 20mg",
    brand: "Square",
    category: "Medicine",
    packSize: "10 capsules",
    defaultSellPrice: 70,
    defaultBarcode: "2800000000179",
    defaultBaseUnit: "strip",
    defaultTrackStock: true,
    aliases: ["gas medicine", "seclo"],
    keywords: ["pharmacy", "medicine"],
    popularityScore: 80,
  },
  {
    businessType: "pharmacy",
    name: "ORS Sachet",
    brand: "Orsaline-N",
    category: "Medicine",
    packSize: "1 sachet",
    defaultSellPrice: 8,
    defaultBarcode: "2800000000186",
    defaultBaseUnit: "pcs",
    defaultTrackStock: true,
    aliases: ["saline", "ors"],
    keywords: ["pharmacy", "hydration"],
    popularityScore: 86,
  },
  {
    businessType: "pharmacy",
    name: "Savlon Liquid",
    brand: "ACI",
    category: "First Aid",
    packSize: "125ml",
    defaultSellPrice: 90,
    defaultBarcode: "2800000000193",
    defaultBaseUnit: "ml",
    defaultTrackStock: true,
    aliases: ["savlon"],
    keywords: ["pharmacy", "antiseptic", "first aid"],
    popularityScore: 74,
  },
  {
    businessType: "mini_wholesale",
    name: "Miniket Rice Sack",
    brand: "ACI",
    category: "Staples",
    packSize: "25kg",
    defaultSellPrice: 2050,
    defaultBarcode: "2800000000209",
    defaultBaseUnit: "carton",
    defaultTrackStock: true,
    aliases: ["rice sack", "chal bosta"],
    keywords: ["wholesale", "bulk", "staple"],
    popularityScore: 94,
  },
  {
    businessType: "mini_wholesale",
    name: "Soybean Oil Carton",
    brand: "Fresh",
    category: "Oil",
    packSize: "5L x 4",
    defaultSellPrice: 3500,
    defaultBarcode: "2800000000216",
    defaultBaseUnit: "carton",
    defaultTrackStock: true,
    aliases: ["oil carton"],
    keywords: ["wholesale", "bulk", "grocery"],
    popularityScore: 88,
  },
  {
    businessType: "mini_wholesale",
    name: "Biscuit Carton",
    brand: "Olympic",
    category: "Snacks",
    packSize: "24 packs",
    defaultSellPrice: 780,
    defaultBarcode: "2800000000223",
    defaultBaseUnit: "box",
    defaultTrackStock: true,
    aliases: ["biscuit box"],
    keywords: ["wholesale", "snacks", "bulk"],
    popularityScore: 76,
  },

  // ── Hardware / সিমেন্ট / ফিটিংস ──
  {
    businessType: "hardware",
    name: "সিমেন্ট (Shah/Crown)",
    category: "সিমেন্ট/বিল্ডিং",
    packSize: "50kg bag",
    defaultSellPrice: 480,
    defaultBaseUnit: "bag",
    defaultTrackStock: true,
    aliases: ["cement", "সিমেন্ট ব্যাগ"],
    keywords: ["cement", "building", "construction"],
    popularityScore: 98,
  },
  {
    businessType: "hardware",
    name: "রড 60 গ্রেড",
    category: "সিমেন্ট/বিল্ডিং",
    defaultSellPrice: 85,
    defaultBaseUnit: "kg",
    defaultTrackStock: true,
    aliases: ["rod", "iron rod", "রড"],
    keywords: ["rod", "construction", "building"],
    popularityScore: 95,
  },
  {
    businessType: "hardware",
    name: "PVC পাইপ",
    category: "পাইপ/ফিটিংস",
    defaultSellPrice: 35,
    defaultBaseUnit: "ft",
    defaultTrackStock: true,
    aliases: ["pipe", "পাইপ", "pvc pipe"],
    keywords: ["pipe", "plumbing", "fitting"],
    popularityScore: 90,
  },
  {
    businessType: "hardware",
    name: "ইলেকট্রিক তার",
    category: "ইলেকট্রিক্যাল",
    defaultSellPrice: 450,
    defaultBaseUnit: "coil",
    defaultTrackStock: true,
    aliases: ["wire", "তার", "electric wire"],
    keywords: ["wire", "electric", "cable"],
    popularityScore: 88,
  },
  {
    businessType: "hardware",
    name: "পেরেক (নেইল)",
    category: "হার্ডওয়্যার",
    defaultSellPrice: 120,
    defaultBaseUnit: "kg",
    defaultTrackStock: true,
    aliases: ["nail", "পেরেক"],
    keywords: ["nail", "hardware", "fastener"],
    popularityScore: 85,
  },
  {
    businessType: "hardware",
    name: "স্ক্রু বক্স",
    category: "হার্ডওয়্যার",
    defaultSellPrice: 60,
    defaultBaseUnit: "box",
    defaultTrackStock: true,
    aliases: ["screw", "স্ক্রু"],
    keywords: ["screw", "hardware", "fastener"],
    popularityScore: 82,
  },
  {
    businessType: "hardware",
    name: "ইট",
    category: "সিমেন্ট/বিল্ডিং",
    defaultSellPrice: 12,
    defaultBaseUnit: "pcs",
    defaultTrackStock: true,
    aliases: ["brick", "ইটা"],
    keywords: ["brick", "building", "construction"],
    popularityScore: 80,
  },
  {
    businessType: "hardware",
    name: "রং (পেইন্ট)",
    category: "রং/কেমিক্যাল",
    defaultSellPrice: 350,
    defaultBaseUnit: "liter",
    defaultTrackStock: true,
    aliases: ["paint", "রং", "colour"],
    keywords: ["paint", "color", "finishing"],
    popularityScore: 78,
  },
  {
    businessType: "hardware",
    name: "টাইলস",
    category: "সিমেন্ট/বিল্ডিং",
    defaultSellPrice: 55,
    defaultBaseUnit: "pcs",
    defaultTrackStock: true,
    aliases: ["tiles", "টাইল"],
    keywords: ["tiles", "floor", "wall", "building"],
    popularityScore: 75,
  },
  {
    businessType: "hardware",
    name: "সুইচ/সকেট",
    category: "ইলেকট্রিক্যাল",
    defaultSellPrice: 45,
    defaultBaseUnit: "pcs",
    defaultTrackStock: true,
    aliases: ["switch", "socket", "সুইচ"],
    keywords: ["switch", "socket", "electric"],
    popularityScore: 72,
  },
];
