// prisma/seed/rbac/constants.ts

export const ROLE_NAMES = [
  "super_admin",
  "admin",
  "agent",
  "owner",
  "staff",
] as const;

export type RoleName = (typeof ROLE_NAMES)[number];

export const PERMISSION_NAMES: string[] = [
  "view_shops",
  "create_shop",
  "update_shop",
  "manage_shop_invoice_feature",
  "delete_shop",
  "switch_shop",
  "view_products",
  "create_product",
  "update_product",
  "delete_product",
  "update_product_stock",
  "update_product_price",
  "manage_product_status",
  "import_products",
  "view_purchases",
  "create_purchase",
  "view_suppliers",
  "create_supplier",
  "create_purchase_payment",
  "view_sales",
  "view_sale_details",
  "view_sales_invoice",
  "create_sale",
  "issue_sales_invoice",
  "update_sale",
  "cancel_sale",
  "create_due_sale",
  "take_due_payment_from_sale",
  "view_customers",
  "create_customer",
  "update_customer",
  "delete_customer",
  "view_due_summary",
  "view_customer_due",
  "create_due_entry",
  "take_due_payment",
  "writeoff_due",
  "view_expenses",
  "create_expense",
  "update_expense",
  "delete_expense",
  "view_cashbook",
  "create_cash_entry",
  "update_cash_entry",
  "delete_cash_entry",
  "adjust_cash_balance",
  "view_reports",
  "view_sales_report",
  "view_expense_report",
  "view_cashbook_report",
  "view_profit_report",
  "view_payment_method_report",
  "view_top_products_report",
  "view_low_stock_report",
  "export_reports",
  "view_users",
  "create_user",
  "update_user",
  "delete_user",
  "view_roles",
  "create_role",
  "update_role",
  "delete_role",
  "assign_role_to_user",
  "revoke_role_from_user",
  "view_users_under_me",
  "create_user_agent",
  "create_user_owner",
  "create_user_staff",
  "edit_users_under_me",
  "delete_users_under_me",
  "access_rbac_admin",
  "view_settings",
  "update_settings",
  "view_dashboard_summary",
  "use_offline_pos",
  "sync_offline_data",
];

export const DEMO_USERS: {
  role: RoleName;
  name: string;
  email: string;
  password: string;
}[] = [
  {
    role: "super_admin",
    name: "Super Admin (Demo)",
    email: "superadmin@pos.test",
    password: "Admin123!",
  },
  {
    role: "admin",
    name: "Admin Manager (Demo)",
    email: "admin@pos.test",
    password: "Admin123!",
  },
  {
    role: "agent",
    name: "Sales Agent (Demo)",
    email: "agent@pos.test",
    password: "Agent123!",
  },
  {
    role: "owner",
    name: "Shop Owner (Demo)",
    email: "owner@pos.test",
    password: "Owner123!",
  },
  {
    role: "staff",
    name: "Staff Member (Demo)",
    email: "staff@pos.test",
    password: "Staff123!",
  },
];
